docs: create package integrators guide
defenseunicorns/uds-marketplace pull request #107
Opened 2024-08-07 23:20 UTC by andrewg-xyz

2024-08-07 23:21 UTC, andrewg-xyz commented
TODO:
- [ ] Review and update with https://coda.io/d/Dougs-Guide-to-the-Galaxy_dEQl5rLfAJv/UDS-Package-Bundle-Creation-Introduction_sua7a#_lusKF
-  [ ] Is uds-marketplace the right repo for this type of documentation?

2024-08-07 23:33 UTC, daveworth commented on docs/package_integration/guide.md
> +3. Adding a UDS package Custom Resrouce `uds-package.yaml` to integrate with UDS Core via Pepr
```suggestion
3. Adding a UDS package Custom Resource `uds-package.yaml` to integrate with UDS Core via Pepr
```

2024-08-07 23:33 UTC, daveworth commented on docs/package_integration/guide.md
> +- Defense Unicorns uses Apache 2.0 licenses exclusively products, see the [Open Source Policy](https://github.com/defenseunicorns/uds-common/blob/main/docs/adrs/0002-apache-2.0-for-all-uds-products.m
```suggestion
- Defense Unicorns uses Apache 2.0 licensed products exclusively, see the [Open Source Policy](https://github.com/defenseunicorns/uds-common/blob/main/docs/adrs/0002-apache-2.0-for-all-uds-products.md).
```

2024-08-07 23:33 UTC, daveworth commented on docs/package_integration/guide.md
> +- UDS generally assumes applications are containerized and can be deployed via Kubernetes. (exceptions are possible, but rare and require additional work e.g. KubeVirt)
```suggestion
- UDS generally assumes applications are containerized and can be deployed via Kubernetes. (exceptions are possible, but rare, and require additional work e.g. KubeVirt)
```

2024-08-07 23:33 UTC, daveworth commented on docs/package_integration/guide.md
> +5. Briefly review [Pepr Documentation](https://docs.pepr.dev/) it may become useful when you begin integrating with UDS Core.
```suggestion
5. Briefly review [Pepr Documentation](https://docs.pepr.dev/): it may become useful when you begin integrating with UDS Core.
```

2024-08-07 23:33 UTC, daveworth commented on docs/package_integration/guide.md
> +- [ ] The Command `uds zarf dev generate` may be useful to generate an initial zarf.yaml file for your application.
```suggestion
- [ ] The Command `uds zarf dev generate` may be useful to generate an initial `zarf.yaml` file for your application.
```

2024-08-08 00:23 UTC, corang requested changes

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +2. Integrating the upstream deployment mechanism (helm, manifests, kustomize, etc...) as a zarf package `zarf.yaml` to build a declarative OCI artifact
We should really only support helm charts

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +3. Adding a UDS package Custom Resrouce `uds-package.yaml` to integrate with UDS Core via Pepr
This needs to be in a helm chart

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +- In other casesVendors in the marketplace will carry forward their license and associated fees.
`casesVendors` typo

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +- [ ] Evaluate the application's deployment mechanism to determine the best Zarf package component (e.g., Helm, Kustomize, etc.).
We should really only support helm charts

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +- [ ] The Command `uds zarf dev generate` may be useful to generate an initial zarf.yaml file for your application.
There's a template repo to generate a uds-package-x repo from that should be used, alternatively uds-common will soon have a proper example package in it in the flavor of nginx

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +3. [UDS Common Repository](https://github.com/defenseunicorns/uds-common): Contains information and best practices for UDS integration.
We should probably call out best practices explicitly here

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +Your goal is to integrate the Zarf package application with [UDS Core](https://github.com/defenseunicorns/uds-core), using `uds-package.yaml` custom resource.
This needs to be in a helm chart

2024-08-08 00:23 UTC, corang commented on docs/package_integration/guide.md
> +- [ ] Have a resourced team explicitly defined for maintenance.
Shouldn't we just reference best practices guide or the issue template for badging here instead of duplicating information?

2024-08-08 00:24 UTC, corang commented
I'm gonna be honest I don't know how to do suggestions or I would've

2024-08-08 01:37 UTC, Racer159 commented
> I'm gonna be honest I don't know how to do suggestions or I would've

Middle button in the comment bar (or `ctrl-g`)

![image](https://github.com/user-attachments/assets/2db13b7f-694c-4c27-9d7f-c38fb84bfc72)

2024-08-08 02:01 UTC, Racer159 commented on docs/package_integration/guide.md
> +- [ ] Have a resourced team explicitly defined for maintenance.
agree this should link to package practices information instead

2024-08-08 02:01 UTC, Racer159 commented on docs/package_integration/guide.md
> +- [UDS Package GitLab](https://github.com/defenseunicorns/uds-package-gitlab) (More complex example)
probably add uds-common here as @corang mentioned - that should become a decent small starter example once he finishes.

2024-08-08 12:41 UTC, austenbryan commented on docs/package_integration/guide.md
> +- This may exclude licenses like AGPLv3 or other copyleft licenses from being a valid choice for UDS integration.
I think we need a legal reading to cover us either way but tend to agree with @Racer159 . I will discuss it with Courtney today and see if this is something LaTise can pick up now that she is integrating back

2024-08-08 18:28 UTC, daveworth commented
@corang "Partially Verified" is "exciting" in that it's because I did know how to suggest changes and @andrewg-xyz knew to accept them 😅 

This speaks to the interesting platform lock-in of verification on GitHub :-/

2024-08-09 15:46 UTC, andrewg-xyz commented
> @corang "Partially Verified" is "exciting" in that it's because I did know how to suggest changes and @andrewg-xyz knew to accept them 😅
> 
> This speaks to the interesting platform lock-in of verification on GitHub :-/

Yeah :/ I suspect I'll have to go mess with git commit history at some point :/

2024-09-09 20:13 UTC, andrewg-xyz commented
Closing in favor of changes here: https://github.com/defenseunicorns/uds-common/pull/226

2024-09-09 20:13 UTC, closed without merging