feat: #68 init golang static server and create initial zarf-package
defenseunicorns/uds-marketplace pull request #98
Opened 2024-08-06 06:14 UTC by mike-winberry

2024-08-07 19:47 UTC, andrewg-xyz requested changes
There is a lot going on here (including with tasks). can you add a `docs/development.md` or similar to articulate what tasks I should care about and caveats?

Specifically suggest:
- how to build & deploy locally
- how to run "dev"
- what should I run before commit/push (linting, tests, etc...)

Happy to discuss details :)

2024-08-07 19:47 UTC, andrewg-xyz commented on tasks/test.yaml
>        - cmd: npx pnpm i && npm run test:unit
help me to understand this line vs
`npx pnpm I && pnpm run test:unit`

2024-08-07 20:02 UTC, mike-winberry commented on tasks/test.yaml
>        - cmd: npx pnpm i && npm run test:unit
which line? one is go one is node? pnpm isn't installed in our actions, probably just need to add it but since its a non-standard package npx ensures it runs. using pnpm run test:unit is the same as npm run test:unit since pnmp requires npm to exist

2024-08-07 20:12 UTC, andrewg-xyz commented on tasks/test.yaml
>        - cmd: npx pnpm i && npm run test:unit
you're answer makes sense :) 

I was poking at pnpm vs npm in the same line. Consider me resolved!

2024-08-07 20:26 UTC, mike-winberry commented
> There is a lot going on here (including with tasks). can you add a `docs/development.md` or similar to articulate what tasks I should care about and caveats?
> 
> Specifically suggest:
> 
> * how to build & deploy locally
> * how to run "dev"
> * what should I run before commit/push (linting, tests, etc...)
> 
> Happy to discuss details :)

I can pull the docs from runtime, its just the standard company tooling? didn't realize our CONTRIBUTING was special, Ill update that.

2024-08-09 04:27 UTC, andrewg-xyz approved these changes

2024-08-09 04:28 UTC, merged